Js2
Christonn93/javascript-2-Noroff pull request #4
Opened 2022-09-19 14:23 UTC by Christonn93

Just want some feedback on the progress so far. 

NOTE! Its far from a finished project, just asking for some feedback along the way to adjust the code to be able to pass this assignment

2022-10-09 08:24 UTC, ShaindalDev commented
I dont have any constructive feedback that will help with progress or anything. But i can say that i do like 99.5% of your setup and solutions. I see now that i should have set a higher standard for my self :) Keep up the great work 100% :)

2022-10-11 11:48 UTC, Fermain commented
I am going to wait on Profile Media update until I provide a full review. My initial impression is that this is feature rich, but needs to be refactored to make it more approachable. Trying to read some of the larger functions was tricky and the only way to handle this is to split things up more.

When dealing with modular JS try to avoid calling functions at the root of a file. Export functions and call them elsewhere otherwise you might find functions running twice.

Finally, for now, please check out the `teacher-review` branch. This is mostly formatting changes, with one or two examples of refactoring. I am not going to do this for your whole project so I recommend you continue in this vain. Prettier can be installed to your project and run as an `npm task` to do this automatically.

2022-10-11 11:57 UTC, Christonn93 commented
> I am going to wait on Profile Media update until I provide a full review. My initial impression is that this is feature rich, but needs to be refactored to make it more approachable. Trying to read some of the larger functions was tricky and the only way to handle this is to split things up more.
> 
> When dealing with modular JS try to avoid calling functions at the root of a file. Export functions and call them elsewhere otherwise you might find functions running twice.
> 
> Finally, for now, please check out the `teacher-review` branch. This is mostly formatting changes, with one or two examples of refactoring. I am not going to do this for your whole project so I recommend you continue in this vain. Prettier can be installed to your project and run as an `npm task` to do this automatically.

I'm already looking into refactoring and changing my functions after a self review. but it have to wait until i have figured out the filter. 
I get the new array in my console. but not displaying the new array in the html. Trying to find a way, that's what made me start refactoring some functions.

2022-10-14 09:43 UTC, Fermain requested changes
This is almost there. Just some remaining bugs to be solved before delivery.

I suggest you spend a second to review the URLs in your a href attributes.

`/profile/` is the same thing as `/profile/index.html`, this is the point of using index files.

Overall, good work and 95% of what needs to be on show is on show.

2022-10-14 09:43 UTC, Fermain commented on src/js/utils/classes/cardClass.mjs
> +    <small class="text-muted">Published ${formattedCreated}</small>
`Published Invalid Date`

2022-10-14 09:43 UTC, Fermain commented on src/js/utils/factory.mjs
> +       <div class="row" id="tags">${tags}</div>
<img width="421" alt="image" src="https://user-images.githubusercontent.com/10801540/195815629-b44a7e14-a207-49d7-9050-74fd3471d6f3.png">

2022-10-14 09:43 UTC, Fermain commented on src/js/utils/factory.mjs
> +       <div class="row" id="tags">${tags}</div>
Also cannot change post media

2022-10-14 09:43 UTC, Fermain commented on src/js/main.mjs
> +      displayPageLoader();
There is nothing to hide this loader, I see it all the time on the profile page.

2022-10-14 09:43 UTC, Fermain commented on pages/feed/index.html
> +           <button id="filter-A_zSort" type="button" class="btn btn-theme text-black" data-filter="A_zSort">Author A - Z</button>
These filter/sort buttons are not working for me.

2022-10-14 09:44 UTC, Fermain commented
Also please resolve the conflicts in this branch. If you aren't sure how to do this you can get in touch with me.

2022-10-14 09:45 UTC, Christonn93 commented on src/js/main.mjs
> +      displayPageLoader();
Do you have any posts ? 
If not, it will display all the time. 

working on a default input.

2022-10-14 09:46 UTC, Christonn93 commented on src/js/utils/classes/cardClass.mjs
> +    <small class="text-muted">Published ${formattedCreated}</small>
this should be resolved by next push. Working on refactoring now and for me it displays. 
But i will look more into that.

2022-10-14 09:46 UTC, Fermain commented on src/js/main.mjs
> +      displayPageLoader();
I am fairly sure I do have posts, but it still needs to be hidden if nothing is found

2022-10-14 09:54 UTC, Christonn93 commented on src/js/utils/classes/cardClass.mjs
> +    <small class="text-muted">Published ${formattedCreated}</small>
![image](https://user-images.githubusercontent.com/46559129/195818786-d40a6eb6-375a-4090-87ed-30abf0e8437f.png)
Should be resolved now

2022-10-14 09:55 UTC, Christonn93 commented on src/js/main.mjs
> +      displayPageLoader();
Any tips on this ?

2022-10-14 09:58 UTC, Christonn93 commented on pages/feed/index.html
> +           <button id="filter-A_zSort" type="button" class="btn btn-theme text-black" data-filter="A_zSort">Author A - Z</button>
Noticed that. 
It have to do with the loader. I will look into that.

2022-10-14 10:46 UTC, Christonn93 commented on src/js/main.mjs
> +      displayPageLoader();
Resolved it

2022-10-14 10:46 UTC, Christonn93 commented on src/js/main.mjs
> +      displayPageLoader();
![image](https://user-images.githubusercontent.com/46559129/195829020-f5ce27fd-b032-4501-a86b-cf620cb3e5c4.png)

2022-10-14 13:59 UTC, Christonn93 commented
> Also please resolve the conflicts in this branch. If you aren't sure how to do this you can get in touch with me.

Think i manage to resolve this.

2022-10-14 14:04 UTC, Christonn93 commented
> This is almost there. Just some remaining bugs to be solved before delivery.
> 
> I suggest you spend a second to review the URLs in your a href attributes.
> 
> `/profile/` is the same thing as `/profile/index.html`, this is the point of using index files.
> 
> Overall, good work and 95% of what needs to be on show is on show.

This is almost there. Just some remaining bugs to be solved before delivery.
 - believe the bugs and changes noted in comments have been addressed and changed accordingly. 
 
I suggest you spend a second to review the URLs in your a href attributes.
/profile/ is the same thing as /profile/index.html, this is the point of using index files.
- This is changed to suggested changes

Overall, good work and 95% of what needs to be on show is on show.
- Please confirm that its at 99%. Know about one bug, asked in forum but as of this moment i have yet to resolved that bug regarding button for removing filter from array.

2022-10-14 14:34 UTC, Fermain commented
> * Please confirm that its at 99%. Know about one bug, asked in forum but as of this moment i have yet to resolved that bug regarding button for removing filter from array.

I will confirm that the remaining bugs are solved and respond

2022-10-14 15:05 UTC, Fermain commented
<img width="195" alt="image" src="https://user-images.githubusercontent.com/10801540/195879678-b891abca-ca4f-4cb3-ac2e-0a9ce996e7ae.png">

The same URL is being requested multiple times each page. This is going to burn your request limit quickly

2022-10-14 15:06 UTC, Fermain commented
Single post view is not loading when testing with `pages/posts/index.html?id=6425`

2022-10-14 15:08 UTC, Fermain commented
<img width="432" alt="image" src="https://user-images.githubusercontent.com/10801540/195880410-3c493d1b-6c10-4295-9435-1a27aff5a815.png">

These filter actions are still not functional. If you can't get them working you should remove them from view

2022-10-14 15:58 UTC, Christonn93 commented
> <img alt="image" width="432" src="https://user-images.githubusercontent.com/10801540/195880410-3c493d1b-6c10-4295-9435-1a27aff5a815.png">
> 
> These filter actions are still not functional. If you can't get them working you should remove them from view

No idea why it dont work for you.. 
it does for me: https://gyazo.com/33086cbbd889e6166131fe08c53cb0d9

2022-10-14 16:09 UTC, Christonn93 commented
> Single post view is not loading when testing with `pages/posts/index.html?id=6425`
> 
> The response is successful but the loading animation never disappears.
> 
> ```
> There was a problem retrieving the user posts ReferenceError: id is not defined
> ```

this should work now when i push

2022-10-14 16:14 UTC, Christonn93 commented
> <img alt="image" width="195" src="https://user-images.githubusercontent.com/10801540/195879678-b891abca-ca4f-4cb3-ac2e-0a9ce996e7ae.png">
> 
> The same URL is being requested multiple times each page. This is going to burn your request limit quickly

Have 0 idea why and how to solve this..

2022-10-16 08:31 UTC, Christonn93 commented
> > <img alt="image" width="432" src="https://user-images.githubusercontent.com/10801540/195880410-3c493d1b-6c10-4295-9435-1a27aff5a815.png">
> > These filter actions are still not functional. If you can't get them working you should remove them from view
> 
> No idea why it dont work for you.. it does for me: https://gyazo.com/33086cbbd889e6166131fe08c53cb0d9
> 
> And i cant remove them, its one of the requirements.. ![image](https://user-images.githubusercontent.com/46559129/195893257-63be27ee-822e-415b-b6f2-e59de8ab3c8a.png)

Should be fixed now

2022-10-16 08:33 UTC, Christonn93 commented
> > <img alt="image" width="195" src="https://user-images.githubusercontent.com/10801540/195879678-b891abca-ca4f-4cb3-ac2e-0a9ce996e7ae.png">
> > The same URL is being requested multiple times each page. This is going to burn your request limit quickly
> 
> Have 0 idea why and how to solve this..

@Fermain Can still not understand why this is happening.

2023-01-27 07:10 UTC, merged